apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: containerofravi/spring-boot-docker
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_HOST
              value: mongo-cluster-ip-service
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongopwd
                  key: MPASSWORD